### ISSUE TITLE
(7380) Some critical error occurred (see log). Disabling the adapter

### ISSUE THREAD

**Issue by FusionJR** [marvingrieger/ioBroker.haassohn#26]
(7380) Hardware / Software version (KS01_V7.02) is not supported by this adapter! Please open an issue on GitHub.
Haas+Sohn Version: 1.0.2
Can you fix that problem, or do you need some more information?
Best Regards 
FusionJR

**Comment by FusionJR** [comment]
I don't understand why it works again now. I deleted all devices again and restarted the adapter. Now it works

**Comment by FusionJR** [comment]
problem is back

**Comment by marvingrieger** [comment]
Hey,

will fix this tomorrow.
Can you tell me the exact name of your oven model? Should be something like "HSP 6 PALLAZZA-III".

Best regards

**Comment by marvingrieger** [comment]
Hey,

since this is an oven, I configured the adapter to terminate itself if an unknown hardware/software version is present.
However, each new combination can be unlocked.

The combination KS01_V7.02 is unlocked in this branch:

https://github.com/marvingrieger/ioBroker.pallazza/tarball/KS01_V7.02

Please install the adapter using this URL and test ...

... if the adapter works as expected
... if you're seeing messages in the log, saying that some states are missing (Message: "State XYZ does not exist")

If everything works as expected, I will merge the branch to the master.

Can you tell me, which oven you're using in particular?
Should be something like "HSP 6 PALLAZZA-III".

Best regards

**Comment by FusionJR** [comment]
Thanks for your reply and your support. I will test it and give you feedback. Sorry for beeing a bit late! Bets regar

**Comment by FusionJR** [comment]
My Oven:
HSP 2.17 Premium III
Software Version : V7.02

**Comment by FusionJR** [comment]
I have installed and tested your version 1.03. 
Unfortunately the same error. I have attached the DebugLog. I hope you can do something with it. Best regards Fusion
======================================
LOG:

haassohn.0 | 2021-02-18 15:30:55.931 | debug | (5045)  stateChange haassohn.0.device.meta.ts  {"val":2289,"ack":true,"ts":*censored*,"q":0,"from":"system.adapter.haassohn.0","user":"system.user.admin","lc":*censored*}
-- | -- | -- | --
haassohn.0 | 2021-02-18 15:30:55.928 | debug | (5045)  stateChange haassohn.0.info.terminated  {"val":true,"ack":true,"ts":*censored*,"q":0,"from":"system.adapter.haassohn.0","user":"system.user.admin","lc":*censored*}
haassohn.0 | 2021-02-18 15:30:55.925 | debug | (5045)  stateChange haassohn.0.info.connection  {"val":false,"ack":true,"ts":*censored*,"q":0,"from":"system.adapter.haassohn.0","user":"system.user.admin","lc":*censored*}
haassohn.0 | 2021-02-18 15:30:55.919 | debug | (5045) Detected new state for device.meta.ts: 2289 (was: 2288)
haassohn.0 | 2021-02-18 15:30:55.918 | error | (5045) Some critical error occurred (see log). Disabling the adapter
haassohn.0 | 2021-02-18 15:30:55.906 | error | (5045) Hardware / Software version (KS01_V7.02) is not supported by this adapter! Please open an issue on GitHub.
haassohn.0 | 2021-02-18 15:30:55.895 | debug | (5045) Syncing state ([object Object]) with path (meta) - false
haassohn.0 | 2021-02-18 15:30:55.893 | debug | (5045) Syncing state ([object Object]) with path () - false
haassohn.0 | 2021-02-18 15:30:55.581 | debug | (5045) Polling device
haassohn.0 | 2021-02-18 15:30:25.645 | debug | (5045)  stateChange haassohn.0.device.is_temp  {"val":11.37,"ack":true,"ts":*censored*,"q":0,"from":"system.adapter.haassohn.0","user":"system.user.admin","lc":*censored*}
haassohn.0 | 2021-02-18 15:30:25.625 | debug | (5045) Detected new state for device.is_temp: 11.37 (was: 11.3)
haassohn.0 | 2021-02-18 15:30:25.607 | debug | (5045)  stateChange haassohn.0.device.meta.ts  {"val":2288,"ack":true,"ts":*censored*,"q":0,"from":"system.adapter.haassohn.0","user":"system.user.admin","lc":*censored*}
haassohn.0 | 2021-02-18 15:30:25.596 | debug | (5045) Detected new state for device.meta.ts: 2288 (was: 2287)
haassohn.0 | 2021-02-18 15:30:25.596 | debug | (5045) HSPIN: *censored*
haassohn.0 | 2021-02-18 15:30:25.569 | debug | (5045) Syncing state ([object Object]) with path (meta) - false
haassohn.0 | 2021-02-18 15:30:25.568 | debug | (5045) Syncing state ([object Object]) with path () - false
haassohn.0 | 2021-02-18 15:30:25.267 | debug | (5045) Polling device
haassohn.0 | 2021-02-18 15:30:25.266 | debug | (5045) HPIN: *censored*
haassohn.0 | 2021-02-18 15:30:25.215 | info | (5045) starting. Version 1.0.3 in /opt/iobroker/node_modules/iobroker.haassohn, node: v14.15.3, js-controller: 3.1.6

**Comment by marvingrieger** [comment]
Hello,
I refactored the unlocking of new versions a little bit, please try again.
However, I should have worked in the first place.

Please make sure, that the adapter is installed correctly.
In particular: Delete the old one first and push _upload_:

<img width="144" alt="Upload" src="https://user-images.githubusercontent.com/1997765/108414494-9773ac80-722c-11eb-8ee2-6e7c7dcb5b2b.png">

If the error still exists, please upload the debug log again.

Best regards

**Comment by FusionJR** [comment]
> Please make sure, that the adapter is installed correctly.
> In particular: Delete the old one first and push _upload_:
> 
> <img alt="Upload" width="144" src="https://user-images.githubusercontent.com/1997765/108414494-9773ac80-722c-11eb-8ee2-6e7c7dcb5b2b.png">

That was the reason. Thanks! Now it works in version 1.0.3 for me fine. Hers the Log:


haassohn.0 | 2021-02-18 22:54:47.383 | debug | (13162)  stateChange haassohn.0.device.is_temp  {"val":8,"ack":true,"ts":*censored*,"q":0,"from":"system.adapter.haassohn.0","user":"system.user.admin","lc":*censored*}
-- | -- | -- | --
haassohn.0 | 2021-02-18 22:54:47.380 | debug | (13162)  stateChange haassohn.0.device.meta.ts  {"val":2492,"ack":true,"ts":1613685287372,"q":0,"from":"system.adapter.haassohn.0","user":"system.user.admin","lc":*censored*}
haassohn.0 | 2021-02-18 22:54:47.370 | debug | (13162) Detected new state for device.is_temp: 8 (was: 7.93)
haassohn.0 | 2021-02-18 22:54:47.368 | debug | (13162) Detected new state for device.meta.ts: 2492 (was: 2491)
haassohn.0 | 2021-02-18 22:54:47.275 | debug | (13162) Hardware / Software version is supported by this adapter! Please open an issue on GitHub.
haassohn.0 | 2021-02-18 22:54:47.271 | debug | (13162) Syncing state ([object Object]) with path (meta) - false
haassohn.0 | 2021-02-18 22:54:47.271 | debug | (13162) Syncing state ([object Object]) with path () - false
haassohn.0 | 2021-02-18 22:54:46.962 | debug | (13162) Polling device

**Comment by marvingrieger** [comment]
Merged to master
