### ISSUE TITLE
KS01_V7.06 - not supported

### ISSUE THREAD

**Issue by Eng-7** [marvingrieger/ioBroker.haassohn#29]
Hi,

unfortunately my Haas&Sohn oven HSP7 is not working anymore with ioBroker. I get following error messages in iobroker:

- Some critical error occurred (see log). Disabling the adapter
- Hardware / Software combination (KS01_V7.06) is not supported by this adapter! Please open an issue on GitHub. 

I think through an update of the oven, is the version number up counted. Could you fix that problem? Thanks a lot!!!

best regards,
Lukas

**Comment by marvingrieger** [comment]
Hey,

KS01_V7.06 is supported / unlocked:
https://github.com/marvingrieger/ioBroker.haassohn/blob/7b154e9916bf7766aa92a9089d9f553cec9cd7a4/io-package.json#L257

Therefore, I assume there is some problem with your installation.
I suggest you try to reinstall the adapter / perform an _upload_ (see https://github.com/marvingrieger/ioBroker.haassohn/issues/28#issuecomment-798873388).

If this does not work, please set the log-level to debug (also, see https://github.com/marvingrieger/ioBroker.haassohn/issues/28#issuecomment-798873388) and post the output here.

Best regards

**Comment by Eng-7** [comment]
Hey,
the reinstall of the adapter solved the problem. Really strange... 😄

Thanks a lot! 👍 

Best regards
