### ISSUE TITLE
What controller

### ISSUE THREAD

**Issue by aceindy** [marvingrieger/ioBroker.haassohn#37]
Hi there,

Not really an issue, but I was wondering what kind of controller is used inside the haas&sohn stoves.
Just curious, as I an also working on a stove, based on a controller from [Duepi Group](https://www.duepigroup.com/en/prodotti-duepi/electronic-control-evo/)

**Comment by marvingrieger** [comment]
Hi,

sorry but I can't help you with that since I don't know. I only reverse engineered the protocol.

Best regards
