### ISSUE TITLE
Same Problem

### ISSUE THREAD

**Issue by Bandit500** [marvingrieger/ioBroker.haassohn#42]
Hello, I also have a problem with the new firmware from Haas und Sohn. Before the update, the adapter worked wonderfully but now it deactivates itself after the message:

Error: (21875) Hardware / Software combination (KS01_V5.07) is not supported by this adapter! Please open an issue on GitHub.

Can you add the HSP 6 Pallazza III with the software V5.07 to the list? I installed version 1.0.5 but unfortunately it doesn't work with my oven. Would be great. Thank you and have a nice evening ... lg ... Bandit500

**Comment by marvingrieger** [comment]
Hello,
I unlocked this Hardware / Software combination in Version 1.0.6, please test this one.
Best regards

**Comment by marvingrieger** [comment]
Resolved (see https://github.com/marvingrieger/ioBroker.haassohn/issues/43)
