### ISSUE TITLE
Work Perfect...

### ISSUE THREAD

**Issue by Bandit500** [marvingrieger/ioBroker.haassohn#43]
Hello, thank you for expanding the adapter. This works great. I updated version 1.0.6 and it works fine. I will observe this over the next few days and give you feedback again. Thanks for the quick help ... have a nice evening ... Bandit500

**Comment by marvingrieger** [comment]
One more question: Usually the oven have some kind of type number like 519.08 or 534.08:

- HSP 6 PALLAZZA-III **519.08** (V5.12)
- HSP 6 PALLAZZA-III **534.08** (V6.02)

Does yours have one too?

**Comment by Bandit500** [comment]
Hello, I have the pellet stove PELLETTO II 434.08-C. The adapter works
great with my oven. Thank you again ...


Am Mo., 15. Nov. 2021 um 20:20 Uhr schrieb Marvin Grieger <
***@***.***>:
