### ISSUE TITLE
KS01_V7.13 is not supported by this adapter!

### ISSUE THREAD

**Issue by fluke101** [marvingrieger/ioBroker.haassohn#44]
Hi,

unfortunately my new Haas&Sohn oven HSP6 is not working anymore with ioBroker. I get following error messages in iobroker:

-----------
Some critical error occurred (see log). Disabling the adapter
Hardware / Software combination (KS01_V7.13) is not supported by this adapter! Please open an issue on GitHub.
-----------
State device.meta.backend_interval does not exist. Please open an issue on GitHub..
-----------
State device.meta.backend_max_diff does not exist. Please open an issue on GitHub..
-----------
State value to set for "haassohn.0.device.meta.ts" has to be type "string" but received type "number"
-----------

Could you fix that problem? Thanks a lot!!!

pellet stove data:
Type: 419.08
Var: HSP6 Pellttino 419.08
Firmware: HSP-6-V7.13

best regards, Hans

**Comment by marvingrieger** [comment]
Hey,
I added your device in v1.0.7. To test it, please install the adapter directly from GitHub:

<img width="993" alt="Bildschirmfoto 2021-12-20 um 20 47 57" src="https://user-images.githubusercontent.com/1997765/146824402-27f1d7e5-e549-4af3-a0ea-bca007ae38ec.png">

It seems like in the firmware you are using, two additional states were added:
- device.meta.backend_interval
- device.meta.backend_max_diff

I added these states. However, I am not sure what they are representing and which kind of types the variables are.
In the current version I added them as strings. If the type if wrong, your might see some errors like the one above:

_State value to set for "haassohn.0.device.meta..." has to be type "XXX" but received type "string"_

If this is the case, please let me know.
In addition, it would be great if you can send me the contents of both states.

Best regards

**Comment by fluke101** [comment]
Hallo Marvin,

vielen dank für die Anpassung des Adapters, er funktioniert fehlerfrei

Ofen Info:
Typ: HSP-6  Pellettino
Fw: v7.13


gruß Hans Stütz
