### ISSUE TITLE
Hardware / Software combination (KS01_V6.01) is not supported by this adapter! Please open an issue on GitHub.

### ISSUE THREAD

**Issue by chrisw87sb** [marvingrieger/ioBroker.haassohn#47]
haassohn.0 | 2022-09-26 14:47:50.103 | error | Some critical error occurred (see log). Disabling the adapter
-- | -- | -- | --
haassohn.0 | 2022-09-26 14:47:50.075 | error | Hardware / Software combination (KS01_V6.01) is not supported by this adapter! Please open an issue on GitHub.

**Comment by marvingrieger** [comment]
Hey,
I added your device in v1.0.8 To test it, please install the adapter directly from GitHub:

![](https://user-images.githubusercontent.com/1997765/146824402-27f1d7e5-e549-4af3-a0ea-bca007ae38ec.png)

Can you please tell me which type of oven you are using specifically?
Also, please let me know if the adapter works for you now. Then I'll publish a new version.

Best regards

**Comment by chrisw87sb** [comment]
Hi!

Ich habe mir erlaubt einen Fork von deinem Projekt anzufertigen und
schonmal zu testen.

Der Adapter funktioniert problemlos.

Ich habe einen Hark Ecomat 6 Pelletofen.

Danke für deine Mühe und Arbeit und liebe Grüße.

Marvin Grieger ***@***.***> schrieb am Sa., 1. Okt. 2022,
23:14:

**Comment by marvingrieger** [comment]
Hey,
super. Mir war gar nicht bewusst, dass Hark dasselbe WLAN-Modul verwendet ... spannend.
Siehst du im Log Fehlermeldungen bzgl. fehlender Zustände? So etwas wie

`State device.meta.backend_max_diff does not exist. Please open an issue on GitHub.`

Beste Grüße

**Comment by chrisw87sb** [comment]
Hey,
nein, da ist mir bisher nichts aufgefallen. Konnte auch alle Stati, die ich brauche abfragen und verändern.

Falls doch mal was kommt, sag ich aber bescheid.
