### ISSUE TITLE
Adapter turn yellow (Hardware / Software combination (KS01_V6.07) is not supported by this adapter)

### ISSUE THREAD

**Issue by mlpriv** [marvingrieger/ioBroker.haassohn#49]
HSP 7 all informations update / poll one time then adapter turn to yellow.
In the Log the following line is displayed:

Hardware / Software combination (KS01_V6.07) is not supported by this adapter! Please open an issue on GitHub.

**Comment by marvingrieger** [comment]
Hey,
I added your device in v1.0.9. To test it, please install the adapter directly from GitHub:

![](https://user-images.githubusercontent.com/1997765/146824402-27f1d7e5-e549-4af3-a0ea-bca007ae38ec.png)

Can you please tell me which type of oven you are using specifically?
Also, please let me know if the adapter works for you now. Then I'll publish a new version.

Best regards

**Comment by mlpriv** [comment]
Thank you - adapter keeps green and update values!
Model: HSP 7
https://www.haassohn.com/de/produkte/archiv/pelletoefen/HSP%207_f-14203
