### ISSUE TITLE
Update stable version in repo from 1.0.7 to 1.0.8

### ISSUE THREAD

**Issue by GermanBluefox** [marvingrieger/ioBroker.haassohn#50]
# Think about update stable version to 1.0.8
**Version**: stable=**1.0.7** (298 days old) => latest=**1.0.8** (67 days old)
**Installs**: stable=**100** (42.37%), latest=**10** (4.24%), total=**236**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L683)

**Comment by marvingrieger** [comment]
Created pull request to update stable to v1.0.9
