### ISSUE TITLE
Some critical error occurred (see log). Disabling the adapter

### ISSUE THREAD

**Issue by Ghett0shot** [marvingrieger/ioBroker.haassohn#51]
Hello,
everytime i get this Error in my Logs after some time the Adapter runs: Hardware / Software combination (KS01_V7.08) is not supported by this adapter!

My Device is an HSP 6 Pelleto IV 419.08.
Software Version is V7.08.

Can you help me with this Issue or should i delete the Adapter?

Best regards

**Comment by marvingrieger** [comment]
Hey,
I added your device in v1.0.10. To test it, please install the adapter directly from GitHub:

![](https://user-images.githubusercontent.com/1997765/146824402-27f1d7e5-e549-4af3-a0ea-bca007ae38ec.png)

Please let me know if the adapter works for and if you see any warning in the log.
If it works as expected, I'll publish a new version.

Best regards

**Comment by Ghett0shot** [comment]
Hello,
thank you for your fast replay. I will install it, test it and let you know if it works :)

**Comment by Ghett0shot** [comment]
About 10 minutes after the adapter startet, this Error Log appears: 

Hardware / Software combination (KS01_V7.08) is not supported by this adapter!
Some critical error occurred (see log). Disabling the adapter

**Comment by marvingrieger** [comment]
That's strange ... can you please increase the log level to debug and share the log output:

<img width="656" alt="Bildschirm­foto 2023-02-12 um 17 31 19" src="https://user-images.githubusercontent.com/1997765/218323761-a001b5dd-78be-41cc-9130-43a787a63e95.png">

**Comment by Ghett0shot** [comment]
![Haassohn](https://user-images.githubusercontent.com/125191552/218326058-3664d39c-90aa-4a35-ab05-43fa5e0288f3.PNG)
Here is the log i got, hope it will help you.

**Comment by marvingrieger** [comment]
Hmmm this output here:

<img width="1359" alt="Bildschirm­foto 2023-02-12 um 18 21 52" src="https://user-images.githubusercontent.com/1997765/218326515-42fcb571-f0a8-43c5-9ced-90069964575d.png">

Should look like this:

<img width="1098" alt="Bildschirm­foto 2023-02-12 um 18 20 54" src="https://user-images.githubusercontent.com/1997765/218326520-0f61e165-b86d-4c38-a55d-d22b8021f710.png">

Somehow the adapter is not able to parse its configuration correctly.
Can you please reinstall the adapter and also perform an upload:

<img width="1086" alt="Bildschirm­foto 2023-02-12 um 18 21 22" src="https://user-images.githubusercontent.com/1997765/218326626-f3b27cb5-70d4-41ba-b169-b4643df0e2c6.png">

**Comment by Ghett0shot** [comment]
I have reinstalled the adapter and uploaded it.

I have also an other Question. Do you speak german? On one of your photos the language was german :D

**Comment by Ghett0shot** [comment]
![Haassohn](https://user-images.githubusercontent.com/125191552/218330345-01327ed5-5ae6-4e05-a64a-efed7ca4ad2c.PNG)

Hello, looks like it works this way :D Since i reinstalled it, there is no error in my log :D

**Comment by marvingrieger** [comment]
Das sieht viel besser aus ;)

Dann schließe ich das Ticket.
Falls es noch Probleme gibt, melde dich.

**Comment by Ghett0shot** [comment]
Super, vielen Dank das du mir da geholfen hast und das an einem Sonntag:D
Schönen Abend noch :D
