### ISSUE TITLE
Getting errors on HSP 2.17 PREMIUM (V5.13)

### ISSUE THREAD

**Issue by Kammi61871** [marvingrieger/ioBroker.haassohn#54]
<html><body>

host.rpi4b | 2023-10-22 07:34:27.320 | error | instance system.adapter.haassohn.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
haassohn.0 | 2023-10-22 07:34:20.612 | warn | get state error: DB closed
haassohn.0 | 2023-10-22 07:34:11.295 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
haassohn.0 | 2023-10-22 07:34:09.088 | error | Cannot read properties of null (reading 'value')
haassohn.0 | 2023-10-22 07:34:09.087 | error | TypeError:  Cannot read properties of null (reading 'value')    at  Immediate.<anonymous>  (/opt/iobroker/node_modules/iobroker.haassohn/main.js:313:53)    at  process.processImmediate (node:internal/timers:478:21)

</body>
</html>

**Comment by marvingrieger** [comment]
Hey,

I haven't seen this error message before. Sounds like a general problem of the connection to the database?
I suggest you try the following steps and check if one of them helps:

1) Reinstall the adapter

2) Re-upload the adapter:
<img width="1161" alt="Upload" src="https://user-images.githubusercontent.com/1997765/111063075-14511980-84ad-11eb-9afa-df34d124e551.png">

3) If this did not solve the problem: Please set the log-level of the adapter to "Debug" and print the output here:

<img width="862" alt="Debug" src="https://user-images.githubusercontent.com/1997765/111063031-c89e7000-84ac-11eb-8ba8-23bf6b190e49.png">

Best regards

**Comment by Kammi61871** [comment]
Reinstall has soved this problem.
