### ISSUE TITLE
HSP2 Premium error

### ISSUE THREAD

**Issue by wer0815** [marvingrieger/ioBroker.haassohn#55]
Hi, ist works fine but I get the error in the Log:

Error:
Some critical error occurred (see log). Disabling the adapter
Hardware / Software combination (KS01_V7.01) is not supported by this adapter! Please open an issue on GitHub.

And there ist no connection, but it works ;-) 
![Bildschirmfoto vom 2023-10-22 17-59-49](https://github.com/marvingrieger/ioBroker.haassohn/assets/148707599/07f92ff9-6622-4c8c-a235-6847b51dc273)

**Comment by marvingrieger** [comment]
Hey,
I added your device in v1.0.11. To test it, please install the adapter directly from GitHub:

Bildschirmfoto 2021-12-20 um 20 47 57

Can you please tell me which type of oven you are using specifically?
Also, please let me know if the adapter works for you now. Then I'll publish a new version.

Best regards

**Comment by wer0815** [comment]
Hey Marvin,
that was fast!

Connected to device or service is green now and it looks like there are no more errors in the log.

Thank you!!!

I`ve the HSP 2.17 Premium-III-2019

![Bildschirmfoto vom 2023-10-22 19-34-21](https://github.com/marvingrieger/ioBroker.haassohn/assets/148707599/c7839217-3ca0-4d42-a27b-90d3cf028a9e)
